version: '3'
services:
  web_app:
    restart: always
    env_file: .env
    build: .
    ports:
      - "5000:5000"
    networks:
      - db_network
      - web_network
    volumes:
      - .:/code
    environment:
      FLASK_ENV: developement
  redis:
    image: "redis:alpine"
  nginx:
    restart: always
    image: "nginx:latest"
    ports:
      - "85:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - web-app
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge